main : Electro\MaintenanceMode\Main
name: MaintenanceMode
version: 1.0.2
api: 4.0.0
author: Electro
description: Adds Maintenance Mode To Your Server

commands:
  mm:
    description: Turn on/off Maintenance Mode
    default: op
    permission: maintenancemode.cmd
    
permissions:
  maintenancemode.cmd:
    default: op
  maintenancemode.bypass:
    default: op
