main : Electro\MaintenanceMode\Main
name: MaintenanceMode
version: 3.0.0
api: 5.0.0
Author: Electro

commands:
  mm:
    description: Activate/Disable Maintenance Mode
    permission: maintenancemode.cmd

permissions:
  maintenancemode.bypass:
    default: op
  maintenancemode.cmd:
    default: op
