main : Electro\RemoteConsole\RemoteConsole
name: RemoteConsole
version: 2.0.0
api: 4.0.0
Author: Electro

commands:
  console:
    description: Send commands through console
    default: true
    permission: remoteconsole.cmd

permissions:
  remoteconsole.cmd:
    default: true
  remoteconsole.password.bypass:
    default: op

