# If set to "true", Maintenance Mode Will Be Active
Maintenance_Mode_Active: false
# Change everything inside of the "" below to set your own message
Maintenance_Mode_Message: "§l§aThis server is Currently Down For Maintenance"
